[build]
builder = "DOCKERFILE"
dockerfilePath = "dockerfile"

[deploy]
healthcheckPath = "/trabajador-salud-app/"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Variables de entorno específicas para Railway
[deploy.env]
PORT = "8080"
JAVA_TOOL_OPTIONS = "-XX:MaxRAMPercentage=75.0"